
/**
 * كتالوج الجهات.
 *
 * `addressee` و`honorific` ليسا تزييناً: هما ما يجعل مخاطبة الديوان الملكي
 * تختلف عن مخاطبة شركة اتصالات. القالب يستخدمهما مباشرة، والـ AI يُبنى
 * سياقه عليهما.
 */

/**
 * الفئات الأولية — تطابق ما يُدرجه ترحيل 20260917000000_department_categories
 * بمعرّفاتها نفسها (`cat_<slug>`)، فالبذر على قاعدة مُرحَّلة لا يُكرّرها.
 */
export const DEPARTMENT_CATEGORIES = [
  { slug: 'government', name: 'جهات حكومية', order: 10 },
  { slug: 'service', name: 'جهات خدمية', order: 20 },
  { slug: 'education', name: 'جهات تعليمية', order: 30 },
  { slug: 'private', name: 'جهات خاصة', order: 40 },
  { slug: 'other', name: 'أخرى', order: 50 },
] as const;

export type DepartmentCategorySlug = (typeof DEPARTMENT_CATEGORIES)[number]['slug'];

export interface DepartmentSeed {
  slug: string;
  name: string;
  nameEn?: string;
  /** `slug` فئة من DEPARTMENT_CATEGORIES. */
  category: DepartmentCategorySlug;
  description: string;
  honorific: string;
  addressee: string;
  order: number;
  /** مفاتيح أنواع الطلبات المتاحة لهذه الجهة. */
  requestTypes: readonly string[];
}

const GOV_COMMON = [
  'complaint',
  'grievance',
  'objection',
  'reconsideration',
  'harm-removal',
  'exception',
  'meeting',
  'other',
] as const;

export const DEPARTMENTS: readonly DepartmentSeed[] = [
  // ---------------------------------------------------------------- حكومية
  {
    slug: 'royal-court',
    name: 'الديوان الملكي',
    nameEn: 'Royal Court',
    category: 'government',
    description:
      'الجهة العليا لرفع المعاريض والطلبات الشخصية والإنسانية التي تعذّر حلّها لدى الجهات المختصة.',
    honorific: 'مقام',
    addressee: 'المقام السامي الكريم',
    order: 1,
    requestTypes: [
      'financial-aid',
      'debt-settlement',
      'treatment',
      'housing',
      'land',
      'grant',
      'support',
      'exception',
      'reconsideration',
      'harm-removal',
      'situation-fix',
      'other',
    ],
  },
  {
    slug: 'regional-emirates',
    name: 'إمارات المناطق',
    nameEn: 'Regional Emirates',
    category: 'government',
    description:
      'إمارة المنطقة — تُرفع إليها الطلبات والشكاوى المحلية وطلبات رفع الضرر والتظلمات.',
    honorific: 'صاحب السمو الملكي',
    addressee: 'صاحب السمو الملكي أمير المنطقة',
    order: 2,
    requestTypes: [
      'financial-aid',
      'debt-settlement',
      'housing',
      'land',
      'support',
      'harm-removal',
      'situation-fix',
      ...GOV_COMMON,
    ],
  },
  {
    slug: 'ministry-interior',
    name: 'وزارة الداخلية',
    nameEn: 'Ministry of Interior',
    category: 'government',
    description: 'الأحوال المدنية، الجوازات، المرور، السجون، والدفاع المدني.',
    honorific: 'معالي',
    addressee: 'معالي وزير الداخلية',
    order: 3,
    requestTypes: ['transfer', 'exception', 'employment', ...GOV_COMMON],
  },
  {
    slug: 'ministry-hrsd',
    name: 'وزارة الموارد البشرية والتنمية الاجتماعية',
    nameEn: 'Ministry of Human Resources and Social Development',
    category: 'government',
    description:
      'الضمان الاجتماعي، الدعم، العمل، حقوق العمال، والجمعيات الأهلية.',
    honorific: 'معالي',
    addressee: 'معالي وزير الموارد البشرية والتنمية الاجتماعية',
    order: 4,
    requestTypes: [
      'financial-aid',
      'debt-settlement',
      'support',
      'employment',
      'exemption',
      ...GOV_COMMON,
    ],
  },
  {
    slug: 'ministry-education',
    name: 'وزارة التعليم',
    nameEn: 'Ministry of Education',
    category: 'government',
    description: 'التعليم العام والجامعي، الابتعاث، ومعادلة الشهادات.',
    honorific: 'معالي',
    addressee: 'معالي وزير التعليم',
    order: 5,
    requestTypes: [
      'transfer',
      'scholarship',
      'exception',
      'reconsideration',
      'employment',
      'promotion',
      ...GOV_COMMON,
    ],
  },
  {
    slug: 'ministry-health',
    name: 'وزارة الصحة',
    nameEn: 'Ministry of Health',
    category: 'government',
    description: 'الخدمات الصحية، العلاج، التحويل الطبي، والمواعيد.',
    honorific: 'معالي',
    addressee: 'معالي وزير الصحة',
    order: 6,
    requestTypes: ['treatment', 'transfer', 'exception', 'employment', ...GOV_COMMON],
  },
  {
    slug: 'ministry-justice',
    name: 'وزارة العدل',
    nameEn: 'Ministry of Justice',
    category: 'government',
    description: 'المحاكم، كتابة العدل، التنفيذ، والتوثيق.',
    honorific: 'معالي',
    addressee: 'معالي وزير العدل',
    order: 7,
    requestTypes: ['grievance', 'objection', 'reconsideration', 'harm-removal', 'meeting', 'complaint', 'other'],
  },
  {
    slug: 'ministry-housing',
    name: 'وزارة الإسكان',
    nameEn: 'Ministry of Housing',
    category: 'government',
    description: 'الدعم السكني، الأراضي المجانية، والتمويل العقاري المدعوم.',
    honorific: 'معالي',
    addressee: 'معالي وزير الشؤون البلدية والقروية والإسكان',
    order: 8,
    requestTypes: ['housing', 'land', 'support', 'exception', ...GOV_COMMON],
  },
  {
    slug: 'ministry-commerce',
    name: 'وزارة التجارة',
    nameEn: 'Ministry of Commerce',
    category: 'government',
    description: 'السجلات التجارية، حماية المستهلك، والمخالفات التجارية.',
    honorific: 'معالي',
    addressee: 'معالي وزير التجارة',
    order: 9,
    requestTypes: ['complaint', 'grievance', 'objection', 'exemption', 'exception', 'reconsideration', 'other'],
  },
  {
    slug: 'ministry-finance',
    name: 'وزارة المالية',
    nameEn: 'Ministry of Finance',
    category: 'government',
    description: 'الميزانية، المستحقات المالية الحكومية، والمطالبات.',
    honorific: 'معالي',
    addressee: 'معالي وزير المالية',
    order: 10,
    requestTypes: ['financial-aid', 'debt-settlement', 'exemption', 'objection', 'grievance', 'reconsideration', 'other'],
  },
  {
    slug: 'ministry-transport',
    name: 'وزارة النقل',
    nameEn: 'Ministry of Transport',
    category: 'government',
    description: 'الطرق، النقل العام، والخدمات اللوجستية.',
    honorific: 'معالي',
    addressee: 'معالي وزير النقل والخدمات اللوجستية',
    order: 11,
    requestTypes: ['harm-removal', 'situation-fix', 'employment', ...GOV_COMMON],
  },
  {
    slug: 'ministry-environment',
    name: 'وزارة البيئة والمياه والزراعة',
    nameEn: 'Ministry of Environment, Water and Agriculture',
    category: 'government',
    description: 'المياه، الزراعة، الثروة الحيوانية، والدعم الزراعي.',
    honorific: 'معالي',
    addressee: 'معالي وزير البيئة والمياه والزراعة',
    order: 12,
    requestTypes: ['support', 'land', 'exemption', 'harm-removal', ...GOV_COMMON],
  },
  {
    slug: 'ministry-islamic-affairs',
    name: 'وزارة الشؤون الإسلامية',
    nameEn: 'Ministry of Islamic Affairs',
    category: 'government',
    description: 'المساجد، الأئمة والمؤذنون، والدعوة والإرشاد.',
    honorific: 'معالي',
    addressee: 'معالي وزير الشؤون الإسلامية والدعوة والإرشاد',
    order: 13,
    requestTypes: ['employment', 'transfer', 'promotion', 'support', ...GOV_COMMON],
  },
  {
    slug: 'ministry-foreign-affairs',
    name: 'وزارة الخارجية',
    nameEn: 'Ministry of Foreign Affairs',
    category: 'government',
    description: 'التأشيرات، التصديقات، وشؤون المواطنين في الخارج.',
    honorific: 'معالي',
    addressee: 'معالي وزير الخارجية',
    order: 14,
    requestTypes: ['exception', 'meeting', 'complaint', 'reconsideration', 'other'],
  },
  {
    slug: 'ministry-investment',
    name: 'وزارة الاستثمار',
    nameEn: 'Ministry of Investment',
    category: 'government',
    description: 'تراخيص الاستثمار، وتمكين المستثمرين.',
    honorific: 'معالي',
    addressee: 'معالي وزير الاستثمار',
    order: 15,
    requestTypes: ['support', 'exception', 'meeting', 'reconsideration', 'complaint', 'other'],
  },
  {
    slug: 'ministry-tourism',
    name: 'وزارة السياحة',
    nameEn: 'Ministry of Tourism',
    category: 'government',
    description: 'تراخيص المنشآت السياحية، والدعم السياحي.',
    honorific: 'معالي',
    addressee: 'معالي وزير السياحة',
    order: 16,
    requestTypes: ['support', 'exception', 'grant', 'complaint', 'objection', 'other'],
  },

  // ---------------------------------------------------------------- خدمية
  {
    slug: 'banks',
    name: 'البنوك',
    nameEn: 'Banks',
    category: 'service',
    description: 'المصارف — جدولة المديونية، الإعفاء من الرسوم، وتسوية القروض.',
    honorific: 'سعادة',
    addressee: 'سعادة مدير البنك',
    order: 20,
    requestTypes: [
      'debt-settlement',
      'exemption',
      'reconsideration',
      'complaint',
      'objection',
      'situation-fix',
      'other',
    ],
  },
  {
    slug: 'finance-companies',
    name: 'شركات التمويل',
    nameEn: 'Finance Companies',
    category: 'service',
    description: 'شركات التمويل والتقسيط — جدولة الأقساط وتسوية المديونية.',
    honorific: 'سعادة',
    addressee: 'سعادة المدير التنفيذي',
    order: 21,
    requestTypes: ['debt-settlement', 'exemption', 'reconsideration', 'complaint', 'situation-fix', 'other'],
  },
  {
    slug: 'insurance-companies',
    name: 'شركات التأمين',
    nameEn: 'Insurance Companies',
    category: 'service',
    description: 'التأمين الصحي والمركبات — المطالبات والاعتراض على الرفض.',
    honorific: 'سعادة',
    addressee: 'سعادة مدير شركة التأمين',
    order: 22,
    requestTypes: ['objection', 'reconsideration', 'complaint', 'treatment', 'exemption', 'other'],
  },
  {
    slug: 'telecom-companies',
    name: 'شركات الاتصالات',
    nameEn: 'Telecom Companies',
    category: 'service',
    description: 'خدمات الاتصالات والإنترنت — الفواتير والاشتراكات والأعطال.',
    honorific: 'سعادة',
    addressee: 'سعادة مدير خدمة العملاء',
    order: 23,
    requestTypes: ['complaint', 'exemption', 'objection', 'situation-fix', 'other'],
  },
  {
    slug: 'utilities',
    name: 'شركات الكهرباء والمياه',
    nameEn: 'Electricity and Water Companies',
    category: 'service',
    description: 'خدمات الكهرباء والمياه — الفواتير والتوصيل والانقطاع.',
    honorific: 'سعادة',
    addressee: 'سعادة مدير الشركة',
    order: 24,
    requestTypes: ['complaint', 'exemption', 'objection', 'harm-removal', 'situation-fix', 'other'],
  },

  // ---------------------------------------------------------------- تعليمية
  {
    slug: 'universities',
    name: 'الجامعات',
    nameEn: 'Universities',
    category: 'education',
    description: 'الجامعات والكليات — القبول، التأجيل، الاعتذار، والمنح.',
    honorific: 'معالي',
    addressee: 'معالي مدير الجامعة',
    order: 30,
    requestTypes: [
      'exception',
      'reconsideration',
      'scholarship',
      'transfer',
      'grievance',
      'employment',
      'meeting',
      'other',
    ],
  },
  {
    slug: 'schools',
    name: 'المدارس',
    nameEn: 'Schools',
    category: 'education',
    description: 'مدارس التعليم العام والأهلي — النقل والقبول والتظلمات.',
    honorific: 'سعادة',
    addressee: 'سعادة مدير المدرسة',
    order: 31,
    requestTypes: ['transfer', 'exception', 'reconsideration', 'complaint', 'exemption', 'other'],
  },
  {
    slug: 'institutes',
    name: 'المعاهد',
    nameEn: 'Institutes',
    category: 'education',
    description: 'المعاهد والمراكز التدريبية — القبول والرسوم والشهادات.',
    honorific: 'سعادة',
    addressee: 'سعادة مدير المعهد',
    order: 32,
    requestTypes: ['exception', 'exemption', 'reconsideration', 'complaint', 'other'],
  },

  // ---------------------------------------------------------------- خاصة
  {
    slug: 'companies',
    name: 'الشركات',
    nameEn: 'Companies',
    category: 'private',
    description: 'شركات القطاع الخاص — التوظيف والترقية والاستقالة والشكاوى.',
    honorific: 'سعادة',
    addressee: 'سعادة المدير التنفيذي',
    order: 40,
    requestTypes: ['employment', 'promotion', 'transfer', 'complaint', 'grievance', 'meeting', 'situation-fix', 'other'],
  },
  {
    slug: 'organizations',
    name: 'المؤسسات',
    nameEn: 'Organizations',
    category: 'private',
    description: 'المؤسسات والهيئات — الطلبات العامة والتعاون.',
    honorific: 'سعادة',
    addressee: 'سعادة المدير العام',
    order: 41,
    requestTypes: ['support', 'employment', 'meeting', 'complaint', 'other'],
  },
  {
    slug: 'charities',
    name: 'الجمعيات الخيرية',
    nameEn: 'Charities',
    category: 'private',
    description: 'الجمعيات الخيرية — طلبات المساعدة والكفالة والدعم.',
    honorific: 'سعادة',
    addressee: 'سعادة رئيس مجلس الإدارة',
    order: 42,
    requestTypes: ['financial-aid', 'debt-settlement', 'treatment', 'support', 'housing', 'grant', 'other'],
  },
  {
    slug: 'other',
    name: 'جهة أخرى',
    category: 'other',
    description: 'لم تجد جهتك؟ اختر هذا الخيار واكتب اسم الجهة بنفسك.',
    honorific: 'سعادة',
    addressee: 'سعادة المسؤول',
    order: 99,
    requestTypes: [
      'financial-aid',
      'debt-settlement',
      'exemption',
      'treatment',
      'employment',
      'transfer',
      'promotion',
      'housing',
      'land',
      'grant',
      'support',
      'exception',
      'meeting',
      'complaint',
      'grievance',
      'objection',
      'reconsideration',
      'harm-removal',
      'situation-fix',
      'other',
    ],
  },
];
